### ISSUE TITLE
Wait until server fully starts

### ISSUE THREAD

**Issue by ghost** [sjoerdmulder/teamcity-agent-docker#2]
I am using teamcity and agent with docker-compose. When agent starts it immediately tries to fetch buildAgent.zip from server, but at this moment server is only starting and isn't listening for connections yet. Here is my testing config:

``` yaml
server:
  image: sjoerdmulder/teamcity
  ports:
    - 8111:8111
  volumes:
    - ./teamcity-storage:/var/lib/teamcity
agent:
  image: sjoerdmulder/teamcity-agent
  links:
    - server
  environment:
    TEAMCITY_SERVER: http://server:8111
```

Please tell me if i do something wrong.

P. S. I tried to initialize ./teamcity-storage before start containers with compose. No effect.
